Add support for Emscripten and Visual Studio
UnrealPowerz/powar pull request #1
Opened 2022-12-23 00:26 UTC by dstaley

This PR adds support for Emscripten (WebAssembly) and compiling using Visual Studio.

Both of these were achieved with the help of CMake, which has replaced the original use of Make. This makes certain things like library management a bit easier across platforms, and provides native Visual Studio integration without adding Visual Studio specific files.

The code was also lightly edited to support Visual Studio's C compiler, which required a few changes:

- Conditional wrapping of things that are available in gcc, but not MVC like `__builtin_unreachable` and `__builtin_expect`
- Using `uintptr_t` instead of `void*`
- Some changes to constant folding since MVC doesn't support it

Additionally, the main loop of the application was lifted to its own function to support Emscripten, which requires passing in the function to `emscripten_set_main_loop_arg`. Arguments for the loop function have been moved to a `render_context_t` type which just contains pointers to the values required to run the loop.

2022-12-23 16:21 UTC, UnrealPowerz commented
Emscripten, CMake AND Visual Studio support -- love it! ❤️ Thank you for the contribution!

Looks great, just a few minor comments.

2022-12-23 16:27 UTC, UnrealPowerz requested changes
My apologies for the `main.c` file BTW, I should really split it out and clean it up one of these days.

Great work!

2022-12-23 16:27 UTC, UnrealPowerz commented on static/app.js
> +const $q = document.querySelector;
```suggestion
const $i = document.getElementById.bind(document);
const $q = document.querySelector.bind(document);
```

2022-12-23 16:27 UTC, UnrealPowerz commented on main.c
> +    (*(*context).ctx).states = 0;
```suggestion
    while (context->ctx->states < STATES_PER_BATCH) {
        int old_states = context->ctx->states;
        pw_step(context->ctx);
        tmrw_update(context->ctx, context->ctx->states - old_states);
        (*(context->count))++;
    }
    //rtc_update(&ctx.rtc);
    //int old_keys = ctx.keys_pressed;
    context->ctx->keys_pressed = sdl_poll(context->ctx->keys_pressed, context->should_redraw);
    // TODO: maybe invert keys pressed ?
    portb_update(&context->ctx->portb, context->ctx->keys_pressed);
    if (*(context->should_redraw)) {
        sdl_draw(&context->ctx->lcd);
        *(context->should_redraw) = 0;
    }

#ifndef __EMSCRIPTEN__
    Uint32 end = SDL_GetPerformanceCounter();
    float seconds_elapsed = (end - start) / (float)SDL_GetPerformanceFrequency();
    int ms_to_sleep = EXEC_BATCH_MS - (int)(seconds_elapsed * 1000);

    // printf("Batch complete: %d states in %.6f s; sleeping for %d ms\n", (*(*context).ctx).states, seconds_elapsed, ms_to_sleep);

    if (ms_to_sleep > 0) {
        SDL_Delay(ms_to_sleep);
    }
#endif // !__EMSCRIPTEN__

    context->ctx->states = 0;
```

2022-12-27 02:34 UTC, dstaley commented
Thanks for the review! I didn't know about the right arrow notation, but that makes that function read _so_ much better, so thank you!

2022-12-28 14:50 UTC, merged